thecodebase/views/admin.py
import logging

from flask import request
from flask import flash
from flask import redirect
from flask import url_for
from flask import render_template
from flask import Blueprint


from thecodebase.lib.wrappers import only_admins
from thecodebase import content

logger = logging.getLogger(__name__)

admin = Blueprint('admin', __name__, template_folder='templates')


@admin.route('/admin/repos', methods=['GET'])
@only_admins
def admin_repos():
    return render_template(
        'admin.html',
        page_title='Github Repositories',
    )


@admin.route('/admin/repos/update-all', methods=['POST'])
@only_admins
def admin_update_all_repos():
    if request.method == 'POST':
        try:
            content.fetch_repos_from_remote(
                username=request.form.get('username'),
                password=request.form.get('password')
            )
        except Exception as error:
            logger.exception(error)
            flash("Login failed.")
    return redirect(url_for('admin.admin_repos'))



@admin.route('/admin/repos/<int:repo_id>/update', methods=['POST'])
@only_admins
def admin_update_repo_by_id(repo_id):
    if request.method == 'POST':
        content.update_repo(repo_id, request.form)
    return redirect(url_for('admin.admin_repos'))

@admin.route('/admin/repos/delete-all', methods=['POST'])
@only_admins
def admin_delete_all_repos():
    if request.method == 'POST':
        content.delete_all_repos()
    return redirect(url_for('admin.admin_repos'))

thecodebase/views/games.py
import json
from datetime import datetime

from flask import session
from flask import render_template
from flask import request
from flask import Blueprint

from thecodebase import content
from thecodebase.lib.sql import Cursor
from thecodebase.lib.wrappers import mobile_not_supported, login_required


games = Blueprint('games', __name__, template_folder='templates')

@games.route('/post-score', methods=['POST'])
def post_score():
    score = request.form['score']
    select_sql = """
    SELECT username, score, time FROM Score
    JOIN users ON users.uid = Score.uid
    ORDER BY score DESC, time DESC
    """
    with Cursor() as cur:
        cur.execute("INSERT INTO Score (score, uid, time) VALUES (%s, %s, %s)", 
            (score, session.get('uid'), datetime.now(),)
        )
        cur.execute(select_sql)
        data = cur.fetchmany(10)

    data_list = []
    for line in data:
        username, score, date = line
        data_list.append([username.replace('ä', 'a').replace('ö', 'o'), score, str(date)])

    return json.dumps(data_list)


@games.route('/games/')
def games_view():
    kwargs = dict(
        game=True,
        bg='gaming_header.jpg',
        page_title='Games'
    )
    return render_template("games.html", **kwargs)

def create_game(phaser_game):
    kwargs = dict(
         game=True,
         bg='gaming_header.jpg',
         page_title=phaser_game.title,
         phaser_game=phaser_game
    )
    games.route('/games/{}/'.format(phaser_game.url), endpoint=phaser_game.url)(
        mobile_not_supported(
                login_required(
                    lambda: render_template('phaser-game.html', **kwargs)
                )
            )
        )

for game in content.games:
    create_game(game)

thecodebase/views/main.py
from flask import Blueprint
from flask import render_template
from flask import send_file

from thecodebase.lib.wrappers import login_required

main = Blueprint('main', __name__, template_folder='templates')


@main.route('/')
def homepage():
    return render_template("home.html", home=True)


@main.route('/my-server/')
@login_required
def my_server():
    kwargs = dict(
        my_server=True,
        bg='programming_header.jpg',
        page_title='My Server'
    )
    return render_template("my_server.html", **kwargs)


@main.route('/about-me/')
@login_required
def about_me():
    kwargs = dict(
        about_me=True,
        bg='glider_header.jpg',
        page_title='About Me'
    )
    return render_template("about_me.html", **kwargs)


@main.route('/download-cv/')
@login_required
def download_cv():
    return send_file('files/cv_elmeri.pdf', attachment_filename='cv_elmeri.pdf')

thecodebase/views/projects.py
from flask import render_template
from flask import Blueprint


from thecodebase.lib.wrappers import login_required
from thecodebase import content


projects = Blueprint('projects', __name__, template_folder='templates')



def create_topic(topic):
    kwargs = dict(
        topic=topic,
        projects=True,
        bg='programming_header.jpg',
        page_title='Projects'
    )
    projects.route('/{}/'.format(topic.url), endpoint=topic.url)(
        login_required(lambda: render_template('projects.html', **kwargs))
    )

for key in content.topics:
    create_topic(key)

thecodebase/views/refactor_ics.py
import json
from datetime import datetime

from flask import request
from flask import flash
from flask import session
from flask import send_file
from flask import render_template
from flask import Blueprint

from thecodebase.lib.sql import Cursor
from thecodebase.lib.refactor_ics import refactor_file
from thecodebase.lib.wrappers import login_required


refactor_ics = Blueprint('refactor_ics', __name__, template_folder='templates')


def refactor_template():

    with Cursor() as cur:
        found = cur.execute("SELECT json FROM Refactor ORDER BY time DESC")
        if found:
            data = json.loads(cur.fetchone()[0].decode('utf-8', 'ignore'))
            lines = [(key, value) for key, value in data.items()]
        else:
            lines = []

    kwargs = dict(
        refactor=True,
        bg='programming_header.jpg',
        page_title='Refactor ICS',
        enumerate=enumerate,
        lines=lines,
    )
    return render_template("refactor-ics.html", **kwargs)


@refactor_ics.route('/refactor-ics/', methods=['GET', 'POST'])
@login_required
def refactor_ics_view():
    if request.method == 'POST':
        if 'ics-file' not in request.files:
            flash('Select file first')
            return refactor_template()

        ics_file = request.files['ics-file']
        if ics_file.filename == '' or not ics_file.filename.endswith('.ics'):
            flash('Select proper filename (.ics)')
            return refactor_template()

        if ics_file:
            try:
                file_io, results = refactor_file(ics_file)
                with Cursor() as cur:
                    cur.execute("INSERT INTO Refactor (json, uid, time) VALUES (%s, %s, %s)",
                                (json.dumps(results, ensure_ascii=False).encode(
                                    'utf-8'), session.get('uid'), datetime.now(),)
                                )
                return send_file(file_io, attachment_filename="refactored.ics", as_attachment=True)
            except ValueError as error:
                refactor_ics.logger.error(
                    "Error processing ics-file: {}\n\nFile content:\n{}".format(error, ics_file.read()))
                flash("Error: Corrupted file")

    return refactor_template()

thecodebase/templates/admin.html
{% extends "main.html" %}

{% block body %}

<!-- Modal -->
<div class="modal fade" id="githubModal" tabindex="-1" role="dialog" aria-labelledby="githubModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="githubModalLabel">Github Sign-in</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ url_for('admin.admin_update_all_repos')}}" method="post">
                <div class="modal-body">
                        <input name="username" value="{{ form['username'] if form }}" type="text" id="inputEmail" class="form-control" placeholder="Username" required autofocus>
                        <input name="password" value="{{ form['password'] if form }}" type="password" id="inputPassword" class="form-control" placeholder="Password" required>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-secondary">Update Repos</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>


<script>

function getForm(repo) {
    $("#editForm").attr("action", `/admin/repos/${repo.repo_id}/update`);
    $("#displayName").attr("value", repo.display_name);
    $("#sequence").attr("value", repo.sequence);
    $("#readmeHtml").val(repo.readme_html);
    if (repo.no_update) {
        $("#noUpdate").attr("checked", true);
    } else {
        $("#noUpdate").removeAttr("checked");
    }
};

</script>


<!-- Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" >
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Edit Repo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="editFormContainer">
                <form id="editForm" action="/admin/repos/${repo.repo_id}/update" method="post">
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="displayName">Display Name</label>
                            <input name="display_name" id="displayName" value="${repo.display_name}" type="text" class="form-control" required autofocus>
                        </div>
                        <div class="form-group">
                                <label for="sequence">Sequence</label>
                                <input name="sequence" id="sequence" value="${repo.sequence}" type="text" class="form-control" required autofocus>
                            </div>
                        <div class="form-check">
                            <input name="no_update" class="form-check-input" type="checkbox" id="noUpdate">
                            <label class="form-check-label" for="noUpdate">
                                Disable updates from Github
                            </label>
                        </div>
                        <div class="form-group">
                            <label for="readmeHtml">Readme HTML</label>
                            <textarea name="readme_html" class="form-control" id="readmeHtml" required rows="10"></textarea>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-primary" type="submit">Save</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



<div class="card-block bg-white">

    <button type="button" class="btn btn-primary mb-4" data-toggle="modal" data-target="#githubModal">
        Update Repos
    </button>
    <form class="mb-4" action="{{ url_for('admin.admin_delete_all_repos')}}" method="post">
        <button class="btn btn-secondary" type="submit">Delete Repos</button>
    </form>

    {% if content.repos %}
    {% set columns = content.repos[0].keys() %}


    <table class="table" style="max-width: 100% !important;">
        <thead class="thead-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Sequence</th>
                <th scope="col">Name</th>
                <th scope="col">Display name</th>
                <th scope="col">Topics</th>
                <th scope="col">Updates Disabled</th>
                <th scope="col">Last Updated</th>
            </tr>
        </thead>
        <tbody>
            {% for repo in content.repos %}
            <tr onclick='getForm({{ repo | tojson }});' data-toggle="modal" data-target="#editModal"  >
                <td >{{ repo['repo_id'] }}</td>
                <td >{{ repo['sequence'] }}</td>
                <td >{{ repo['name'] }}</td>
                <td >{{ repo['display_name'] }}</td>
                <td >{{ repo['topics'] }}</td>
                <td class="text-center">
                    <input type="checkbox" disabled {{ "checked" if repo['no_update'] else "" }}>
                </td>
                <td >{{ repo['update_date'] }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}

</div>
{% endblock %}

thecodebase/templates/games.html
{% extends "main.html" %}

{% block head %}

<link href="{{ url_for('static', filename='css/hoverable.css') }}" rel="stylesheet">

{% endblock %}

{% block widebody %}


{% endblock %}

{% block body %}
<div class="row">
    {% for game in content.games %}
    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card" style="min-height:26rem" onclick="location.href = '{{ game.url }}/';">
            <img class="img-fluid align-self-center m-4"
                src="{{ url_for('static', filename=game.image) }}" alt="Card image cap"
                style="max-width: 14rem; max-height: 8rem; overflow:hidden">
            <div class="card-body">
                <h5 class="card-title">{{ game.title }}</h5>
                <p class="card-text">{{ game.description }}</p>
                <a href="{{ game.url }}" class="btn btn-secondary">View</a>
            </div>
        </div>

    </div>
    {% endfor %}
</div>

{% endblock %}

thecodebase/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
    <div class="nav-wrapper container">
        <a class="navbar-brand" href="/">
            <img style="max-width:160px;" src="{{ url_for('static', filename='images/mainlogo.png') }}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {{'active' if home }}">
                    <!-- <span class="sr-only">(current)</span> -->
                    <a class="nav-link" href="/">Home</a>
                </li>
                
                <li class="nav-item dropdown {{'active' if projects }}">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Projects
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for topic in content.topics %}
                        <a class="dropdown-item" href="/{{ topic.url }}/">{{ topic.title }}</a>
                        {% endfor %}
                    </div>
                </li>
                <li class="nav-item {{'active' if game }}">
                    <a class="nav-link" href="/games/">Games</a>
                </li>

                <li class="nav-item {{'active' if about_me }}">
                    <a class="nav-link" href="/about-me/">About Me</a>
                </li>
                <li class="nav-item {{'active' if my_server }}">
                    <a class="nav-link" href="/my-server/">My Server</a>
                </li>
                {% if not session.logged_in %}
                <li class="nav-item {{'active' if signing }}">
                    <a class="nav-link" href="/login/">Sign in</a>
                </li>
                {% else %}
                <li class="nav-item {{'active' if signing }}">
                    <a class="nav-link" href="/logout/">Log out</a>
                </li>
                {% endif %}
            </ul>
            <form class="form-inline">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            </form>
        </div>
    </div>
</nav>

thecodebase/templates/home.html
{% extends "main.html" %}

{% block head %}

<link href="{{ url_for('static', filename='css/hoverable.css') }}" rel="stylesheet">

{% endblock %}

{% block widebody %}


{% endblock %}

{% block body %}
<div class="row">
    {% for topic in content.topics %}
    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card" style="min-height:26rem" onclick="location.href = '{{ topic.url }}';">
            <img class="img-fluid align-self-center m-4"
                src="{{ url_for('static', filename=topic.image) }}" alt="Card image cap"
                style="max-width: 14rem; max-height: 8rem; overflow:hidden">
            <div class="card-body">
                <h5 class="card-title">{{ topic.title }}</h5>
                <p class="card-text">{{ topic.description }}</p>
                <a href="/{{ topic.url }}/" class="btn btn-secondary">View</a>
            </div>
        </div>

    </div>
    {% endfor %}
</div>

{% endblock %}

thecodebase/templates/login.html
{% extends "main.html" %}

{% block head %}

    <link href="{{ url_for('static', filename='css/login.css') }}" rel="stylesheet">

{% endblock %}



{% block body %}

<div class="card-block bg-white">

    <div class="container text-center">

        <form action=""  class="form-signin" method="post">
            <img class="mb-4 img-fluid" src="{{ url_for('static', filename='images/mainlogo.png') }}" alt="" style="max-height: 72px;">
            <h1 class="h3 mb-4 font-weight-normal">Sign in</h1>
            <input name="emailUsername" value="{{ form['emailUsername'] if form }}" type="text" id="inputEmail" class="form-control" placeholder="Email or username" required autofocus>
            <input name="password" value="{{ form['password'] if form }}" type="password" id="inputPassword" class="form-control" placeholder="Password" required>
            <div class="checkbox mb-3">
                <label>
                    <input type="checkbox" value="remember-me"> Remember me
                </label>
            </div>
            <button class="btn btn-lg btn-secondary btn-block" type="submit">Sign in</button>
        </form>
        <p>New user? <a href="/register/">Sign up here</a></p>
        <p>{{ error }}</p>
        
    </div>
</div>

{% endblock %}

thecodebase/templates/main.html
<!doctype html>
<html lang="en">
  <head>
  	<meta charset="utf-8">
	<title>The Codebase</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="{{ url_for('static', filename='css/bootstrap/bootstrap.min.css') }}" rel="stylesheet">
	<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

	<link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">

	<script
		src="https://code.jquery.com/jquery-3.3.1.min.js"
		integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
		crossorigin="anonymous">
	</script>
	
	<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap/bootstrap.min.js') }}"></script>

	{% block head %}{% endblock %}

</head>

<header>
		{% include 'header.html' %}
</header>


<body>

	{% with messages = get_flashed_messages() %}
	{% if messages %}
	{% for message in messages %}
	<div id="fading-alert" class="alert alert-warning alert-dismissible text-center" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
		{{message}}
	</div>
	{% endfor %}
	{% endif %}
	{% endwith %}
	<script>
		$("#fading-alert").fadeTo(3000, 500).slideUp(500, function(){
			$("#fading-alert").slideUp(500);
		});
	</script>

	 <!-- page-header -->
	 <div class="page-header" style=" background: url({{ url_for('static', filename='images/%s' % bg) }})no-repeat; position: relative; background-size: cover; background-position: 50%;">
		<div class="container">
			<div class="row">
				<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
					<div class="page-caption text-center">
						<h1 class="page-title">{{ page_title }}</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	

	<div class="container mt-4" style="margin-bottom: 200px;">
		<div class="card-section">
			{% block body %}{% endblock %}
			<div class="row m-4">
				<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 text-center">
					Created by <a href="https://www.thecodebase.site/" >The Codebase</a>
				</div>
			</div>
		</div>
	</div>

	
</body>




</html>

thecodebase/templates/my_server.html
{% extends "main.html" %}






{% block body %}

<div class="card-block bg-white">
    <div class="text-center">
        <h3>The Codebase</h3>
        <p>
            <a href="https://github.com/thecodebasesite/thecodebase" class="badge badge-light ">Github Repository</a>
        </p>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-12 mt-4">
            <img src="{{ url_for('static', filename='images/server_combined.jpg') }}" class="img-fluid float-center" alt="Responsive image"/>
        </div>
        <div class="col-lg-6 col-md-12">
            <p class="m-4">
                This website is built using Python's 
                <a href="http://flask.pocoo.org/">Flask library</a> 
                and styled
                <a href="https://getbootstrap.com/docs/4.1/getting-started/introduction/">Bootstrap v4.1.3.</a> 
                It's  running on the laptop 
                <a href="https://www.lenovo.com/fi/fi/laptops/thinkpad/t-series/ThinkPad-T480/p/22TP2TT4800">(Lenovo ThinkPad T480)</a>
                    shown in the pictures. Deplyoying the server cost me only the domain name ($1.46).
                    I deployed it using the following instructions:
                <ul class="text-left">
                    <li>
                        <a href="https://www.digitalocean.com/community/tutorials/how-to-deploy-a-flask-application-on-an-ubuntu-vps">
                            How To Deploy a Flask Application on an Ubuntu VPS
                        </a>
                    </li>
                    <li>
                        <a href="https://blog.mindorks.com/how-to-convert-your-laptop-desktop-into-a-server-and-host-internet-accessible-website-on-it-part-1-545940164ab9">
                            How to convert your laptop/desktop into a server and host internet accessible website on it
                        </a>
                    </li>
                    <li>
                        <a href="https://letsencrypt.org/getting-started/">
                            Enabling HTTPS with Let's Encrypt
                        </a>
                    </li>
                    <li>
                        <a href="https://pythonprogramming.net/practical-flask-introduction/">
                            Introduction to Practical Flask
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/thecodebasesite/apache2-conf">
                            Configuring Apache2 to force WWW on HTTP host
                        </a>
                    </li>
                    <li>
                        <a href="https://www.hostinger.com/">
                            Cheap domain from Hostinger
                        </a>
                    </li>
                </ul>
            </p>
        </div>
    </div>
</div>
{% endblock %}

thecodebase/templates/phaser-game.html
{% extends "main.html" %}

{% block head %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/phaser/phaser.min.js') }}"></script>
    <style>
        #canvas-container {
            width: 100%;
            text-align:center;
        }
        
        canvas {
            display: inline;
        }
    </style>  
    {% for file in phaser_game.files %}
        <script type="text/javascript" src="{{ url_for('static', filename='%s/%s' % (phaser_game.folder, file) ) }}"></script>
    {% endfor %}

{% endblock %}

{% block body %}
<div class="card-block bg-white">

    <div id="canvas-container">
        <canvas id="gameCanvas">Canvas not supported in your browser</canvas>

        <script type="text/javascript" src="{{ url_for('static', filename='%s/%s' % (phaser_game.folder, phaser_game.files[0]) ) }}"></script>
            
    </div>
</div>
    

{% endblock %}

thecodebase/templates/projects.html
{% extends "main.html" %}

{% block body %}
<div class="card-block bg-white">

    <h1 class="display-4 mb-4 text-center">{{ topic.title }}</h1>
    <ul class="nav nav-tabs nav-fill" id="myTab" role="tablist">        
        {% for repo in topic.repos %}
        <li class="nav-item">
            <a class="nav-link {{ 'active' if repo == topic.repos[0] }} text-dark" id="{{ repo.name }}-tab" data-toggle="tab" href="#{{ repo.name }}" role="tab" aria-controls="{{ repo.name }}" aria-selected="false">{{ repo.display_name }}</a>
        </li>
        {% endfor %}
    </ul>
    <div class="tab-content" id="myTabContent">
        {% for repo in topic.repos %}
        <div class="tab-pane fade mt-4 {{ 'show active' if repo == topic.repos[0] }}" id="{{ repo.name }}" role="tabpanel" aria-labelledby="{{ repo.name }}-tab">
            <div class="container pt-4">
                <p class="text-center">
                    <a href="https://github.com/thecodebasesite/{{ repo.name }}" class="badge badge-light ">Github Repository</a>
                </p>
                <div class="readme m-4">
                    {{ repo.readme_html | safe }}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <script>
        // Javascript to enable link to tab
        var url = document.location.toString();
        if (url.match('#')) {
            $('.nav-tabs a[href="#' + url.split('#')[1] + '"]').tab('show');
        } 
    </script>

</div>
{% endblock %}

thecodebase/templates/refactor-ics.html
{% extends "main.html" %}






{% block body %}


<script type="text/javascript">
  function submitAndRedirect() {
      document.sendFile.submit();
      setTimeout(function() {
          location.href = "{{ url_for('refactor_ics') }}";
      }, 500);
  }
</script>


<div class="card-block bg-white text-center">
    <h1>Refactoring tool for shitty Aalto .ics</h1>
    <br>
    <form name="sendFile"  class="form" method="post" enctype="multipart/form-data">
        <div class="custom-file">
            <input name="ics-file" type=file class="custom-file-input" id="customFile"  onchange="$(this).next().after().text($(this).val().split('\\').slice(-1)[0])">
            <label class="custom-file-label" for="customFile">Choose .ics file</label>
        </div>


        
        <button onclick="submitAndRedirect()" class="btn btn-outline-secondary m-4">Refactor file</button>
      </form>

    
    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Original</th>
            <th scope="col">Refactored</th>
          </tr>
        </thead>
        <tbody>
        {% for index, line in enumerate(lines, start=1) %}
          <tr>
            <th scope="row">{{ index }}</th>
            <td>{{ line[0] }}</td>
            <td>{{ line[1] }}</td>
          </tr>
          
        {% endfor %}
        </tbody>
      </table>
      

</div>


{% endblock %}

thecodebase/templates/register.html
{% extends "main.html" %}

{% block head %}

    <link href="{{ url_for('static', filename='css/login.css') }}" rel="stylesheet">


{% endblock %}


{% block body %}
        
<div class="card-block bg-white">

    <div class="container text-center">
        <form class="form-signin" role="form" autocomplete="off" method="post">
            <img class="mb-4 img-fluid" src="{{ url_for('static', filename='images/mainlogo.png') }}" alt="" style="max-height: 72px;">
            <h1 class="h3 mb-4 font-weight-normal">Register</h1>
            <input value="{{ form['username'] if form }}" name="username" type="text" class="form-control" id="inputName" placeholder="Username" required autofocus></input>
            <input value="{{ form['email'] if form }}" name="email" type="email" class="form-control" id="inputEmail" placeholder="Email address" required>
            <input value="{{ form['password'] if form }}" name="password" type="password" class="form-control" id="inputPassword" placeholder="Password" title="At least 6 characters with letters and numbers" required>
            <input value="{{ form['confirmPassword'] if form }}" name="confirmPassword" type="password" class="form-control" id="inputVerify" placeholder="Retype password" required>
            <button type="submit" class="btn btn-lg btn-secondary btn-block">Register</button>
        </form>
        <p>Already registered? <a href="/login/">Sign in</a></p>
    </div>
</div>
<script type="text/javascript" src="{{ url_for('static', filename='js/validator.js') }}"></script>
{% endblock %}